services:
  utils:
    build: .
    container_name: utils
    hostname: utils
    user: "node"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ~/.ssh:/home/node/.ssh
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]

volumes:
  node_modules: